### ISSUE TITLE
Add to my React framework

### ISSUE THREAD

**Issue by MurageKibicho** [MrBisquit/BST-Trackers#1]
Good morning, 
I hope this message finds you well. I found impressive your library and I hope to implement some functions in the [create-new-startup](https://github.com/kibichomurage/create-new-startup) bundler. 

I was writing to formally seek your permission before I implemented a portion of your codebase. I'm only taking functions that interest me. Is there an attribution style you prefer? Thank you.

**Comment by MrBisquit** [comment]
Yes, take whatever you need. Please do credit me though. Hope it goes well and if there's any question just let me know and I'm sure I can help!

**Comment by MrBisquit** [comment]
Sorry I took so long to respond @MurageKibicho Outlook broke so it didn't tell me that I have new emails. But thanks for asking!

**Comment by MurageKibicho** [comment]
That's fine. Thank you!
